management:
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"